# Sets the docker image for the job
image: node:20

# Build static page
.build-page:
  before_script:
    - corepack enable
    - corepack prepare pnpm@11.0.9 --activate
  script:
    - pnpm install --frozen-lockfile
    - pnpm build
    - mkdir public
    - mv dist/* public

.upload-artifacts:
  artifacts:
    paths:
      - public

# Setup GitLab Pages
pages:
  extends:
    - .build-page
    - .upload-artifacts
  cache:
    paths:
      - node_modules
      - .pnpm-store
  stage: deploy
  only:
    - develop
